import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <>
    <html lang="en">
      <body className={`${inter.className} [background:radial-gradient(50%_50%_at_50%_50%,_#084675,_#01090f)] text-whitesmoke `}>{children}</body>
    </html>
  </>
  );
}
